### ISSUE TITLE
localhost, 127.0.0.1 with HTTP by default

### ISSUE THREAD

**Issue by qinwf** [Rob--W/https-by-default#10]
Thanks for this plugin. It will be great to add a feature to use HTTP for localhost, 127.0.0.1 by default. When doing web dev, this is very helpful.

Or add a list of websites which are loaded with HTTP by default.

**Comment by Rob--W** [comment]
I'm thinking of adding a button to navigate to http when https is unsupported, and an option to remember the choice for X days.
