### ISSUE TITLE
Plans to write a Web Extensions version?

### ISSUE THREAD

**Issue by fmarier** [Rob--W/https-by-default#12]
The README says that the Chrome API for extensions is not powerful enough to enable https-by-default. Have you looked at the Web Extensions API?

**Comment by Rob--W** [comment]
WebExtensions do not (yet?) offer APIs to intercept and modify the typed URL (or to distinguish between typing `http://example.com`, `https://example.com` or `example.com`).

I think that the closest approximation is to unconditionally use https for all top-level requests that are not initiated by a web page (and offer the ability to use the http version if the https site cannot be reached).

**Comment by fmarier** [comment]
I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1370388 to propose the API you suggested above.

**Comment by crssi** [comment]
@fmarier By your experiences, what is ETA for the API to be implemented?

**Comment by fmarier** [comment]
The priority has been set to P5, which means: "we're not going to work on it, but patches welcome."
