### ISSUE TITLE
Pale Moon support?

### ISSUE THREAD

**Issue by ghost** [Rob--W/https-by-default#19]
Hi,

Could you add support for Pale Moon?
Thank you.

**Comment by Rob--W** [comment]
The current extension is a WebExtension.

I am not interested in maintaining a bootstrapped add-on for Pale Moon, but those who are interested can fork the project at https://github.com/Rob--W/https-by-default/commit/a61e880960128ba3031e8dc04bd2dac4b51832e4 and add the Pale Moon's application ID to install.rdf.
