### ISSUE TITLE
Cannot open http links embedded on https sites in a new tab

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/https-by-default#2]
1. Build the Firefox add-on (`make firefox`).
2. Install it.
3. Visit example.com (you'll end up at https://example.com)
4. Click on the link (middle-click, right-click, ctrl-click, etc.) to open it in a new tab.

Expected result:
- The link target, http://www.iana.org/domains/example, should be opened in a new tab.

Actual result:
- Nothing appears to happen. The browser console shows the following error message:
  
  > uncaught exception: Load of http://www.iana.org/domains/example from https://example.com/ denied

The error seems to originate from https://hg.mozilla.org/mozilla-central/file/f214df6ac75f/toolkit/modules/BrowserUtils.jsm#l55.

I pulled the add-on from AMO since this is quite a critical bug.

**Comment by Lekensteyn** [comment]
Clarification: this always happens on opening new tabs via a link, for example by menu navigation, not just by mouse actions.

**Comment by Rob--W** [comment]
Fixed with the new implementation.
