### ISSUE TITLE
Search engines affected

### ISSUE THREAD

**Issue by pyhedgehog** [Rob--W/https-by-default#6]
## Problem

Search engine that has no https support is unusable (I'm using [yubnub](http://www.yubnub.org)) at least on Firefox for Android which has no ability to edit search engine configuration except delete.
## Steps to reproduce
1. Install this extension.
2. Go to http-only search site.
3. Install it as a search engine by long-tap on search bar...
4. Attempt to search with this search engine.
## Actual result

Connection error
## Wanted result

Use of http connection as it's installed.
## Note

I will be happy with workaround like white-list http-only domains.

**Comment by Rob--W** [comment]
I tried to follow your steps in Firefox 47 and Firefox 48 for Mobile (Firefox Beta), but can't reproduce the problem.

At step 4, "Attempt to search with this search engine.", I typed "test" in the address bar, and then tapped on the yubnub search engine. The result is that I ended up on some search result.

Could you provide some more details about reproducing this issue? If you feel that a video makes things clearer, by all means post a video.

**Comment by magicgoose** [comment]
I'd vote for not providing any pre-made exclusion lists. At most there should be possibility to manually add exceptions, but the list should be empty at the beginning.  
Because this is taking too much responsibility, and other websites will change, without notifying the project.

**Comment by pyhedgehog** [comment]
After reinstalling search engine (on current fx version) — no problem.
