### ISSUE TITLE
Not compatible with Tab Utilities

### ISSUE THREAD

**Issue by reallyuniquename** [Rob--W/https-by-default#7]
Usefull addon, unfortunately it's not compatible with TabUtils - https://addons.mozilla.org/en-US/firefox/addon/tab-utilities-fixed/

Steps to reproduce:
1. Install Tab Utils Fixed
2. Install HTTPS by default
3. Restart browser (it's important)
New tabs can't be opened via clicking links or keyboard shortcuts.

**Comment by Rob--W** [comment]
Fixed and submitted update to AMO.
